# Generated by Django 3.2.23 on 2024-01-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ספק',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('שם', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='קטגוריה',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('שם', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='מוצר',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('שם', models.CharField(max_length=100)),
                ('קטגוריה', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.קטגוריה')),
            ],
        ),
        migrations.CreateModel(
            name='הזמנה',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('כמות', models.IntegerField()),
                ('תאריך', models.DateField()),
                ('מוצר', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.מוצר')),
                ('ספק', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.ספק')),
            ],
        ),
    ]
