# Generated by Django 3.2.23 on 2024-01-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_הזמנה_מוצר_ספק_קטגוריה'),
    ]

    operations = [
        migrations.AddField(
            model_name='מוצר',
            name='כמות_במלאי',
            field=models.IntegerField(default=0),
        ),
    ]
