# Generated by Django 3.2.23 on 2024-01-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_מוצר_כמות_במלאי'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='מוצר',
            name='כמות_במלאי',
        ),
    ]
