# Generated by Django 3.2.23 on 2024-01-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_מוצר_כמות_במלאי'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
